namespace CodeMap.Roslyn.Tests.Extraction.Razor;

using CodeMap.Roslyn.Extraction.Razor;
using FluentAssertions;

/// <summary>
/// Verifies <see cref="RazorSgHelpers.ParseChecksumPath"/> handles the realistic
/// shapes of Razor SG output and rejects malformed or absent directives.
/// </summary>
public class ParseChecksumPathTests
{
    [Fact]
    public void HappyPath_FirstLineDirective_ReturnsPath()
    {
        var content = "#pragma checksum \"C:\\src\\App\\Pages\\Counter.razor\" \"{8829d00f-11b8-4213-878b-770e8597ac16}\" \"ABCDEF\"";
        RazorSgHelpers.ParseChecksumPath(content)
            .Should().Be(@"C:\src\App\Pages\Counter.razor");
    }

    [Fact]
    public void LeadingWhitespace_StillMatches()
    {
        var content = "    #pragma checksum \"App/Pages/Counter.razor\" \"{guid}\" \"hash\"";
        RazorSgHelpers.ParseChecksumPath(content)
            .Should().Be("App/Pages/Counter.razor");
    }

    [Fact]
    public void DirectiveOnLineSix_AfterPrelude_StillFound()
    {
        var content = string.Join('\n',
            "// <auto-generated/>",
            "#nullable disable",
            "",
            "// generated comment",
            "// another",
            """#pragma checksum "App/Pages/Weather.razor" "{guid}" "hash" """);

        RazorSgHelpers.ParseChecksumPath(content)
            .Should().Be("App/Pages/Weather.razor");
    }

    [Fact]
    public void DirectiveBeyondScanWindow_ReturnsNull()
    {
        // Directive on line 11 — past the 10-line scan budget.
        var lines = new List<string>();
        for (int i = 0; i < 10; i++) lines.Add("// filler");
        lines.Add("""#pragma checksum "App/Late.razor" "{guid}" "hash" """);
        var content = string.Join('\n', lines);

        RazorSgHelpers.ParseChecksumPath(content).Should().BeNull();
    }

    [Fact]
    public void NoDirective_PlainCSharp_ReturnsNull()
    {
        var content = """
            namespace App;
            public class Foo { }
            """;
        RazorSgHelpers.ParseChecksumPath(content).Should().BeNull();
    }

    [Fact]
    public void Malformed_MissingTrailingTokens_Rejected()
    {
        // Looks like a checksum but the trailing two quoted tokens are missing.
        // The brittle parser would have accepted this; the regex form rejects it.
        var content = """#pragma checksum "App/Foo.razor" """;
        RazorSgHelpers.ParseChecksumPath(content).Should().BeNull();
    }

    [Fact]
    public void CommentMentioningDirective_IsNotMatched()
    {
        var content = """// example: #pragma checksum "fake.razor" "{guid}" "hash" """;
        RazorSgHelpers.ParseChecksumPath(content).Should().BeNull();
    }

    [Fact]
    public void WindowsLineEndings_HandledCorrectly()
    {
        var content = "// header\r\n#pragma checksum \"App/W.razor\" \"{guid}\" \"hash\"\r\n";
        RazorSgHelpers.ParseChecksumPath(content)
            .Should().Be("App/W.razor");
    }

    [Fact]
    public void NullOrEmpty_ReturnsNull()
    {
        RazorSgHelpers.ParseChecksumPath(null).Should().BeNull();
        RazorSgHelpers.ParseChecksumPath("").Should().BeNull();
    }
}
