namespace CodeMap.Query.Tests;

using CodeMap.Core.Enums;
using CodeMap.Core.Interfaces;
using CodeMap.Core.Models;
using CodeMap.Core.Types;
using FluentAssertions;
using NSubstitute;

public sealed class CodebaseSummarizerTests
{
    private static readonly RepoId Repo = RepoId.From("summarizer-repo");
    private static readonly CommitSha Sha = CommitSha.From(new string('b', 40));

    private readonly ISymbolStore _store = Substitute.For<ISymbolStore>();

    private void SetupFacts(FactKind kind, params string[] values)
    {
        var facts = values.Select((v, i) => new StoredFact(
            SymbolId: SymbolId.From($"M:Test.Method{i}"),
            StableId: null,
            Kind: kind,
            Value: v,
            FilePath: FilePath.From("Test.cs"),
            LineStart: i + 1,
            LineEnd: i + 1,
            Confidence: Confidence.High)).ToList<StoredFact>();

        _store.GetFactsByKindAsync(Repo, Sha, kind, Arg.Any<int>(), Arg.Any<CancellationToken>())
              .Returns(facts);
    }

    private void SetupNoFacts(FactKind kind)
        => _store.GetFactsByKindAsync(Repo, Sha, kind, Arg.Any<int>(), Arg.Any<CancellationToken>())
                 .Returns(Array.Empty<StoredFact>());

    private void SetupAllFactsEmpty()
    {
        foreach (FactKind kind in Enum.GetValues<FactKind>())
            SetupNoFacts(kind);
    }

    private void SetupProjectDiagnostics(params ProjectDiagnostic[] diags)
        => _store.GetProjectDiagnosticsAsync(Repo, Sha, Arg.Any<CancellationToken>())
                 .Returns((IReadOnlyList<ProjectDiagnostic>)diags.ToList());

    private void SetupSemanticLevel(SemanticLevel level)
        => _store.GetSemanticLevelAsync(Repo, Sha, Arg.Any<CancellationToken>())
                 .Returns((SemanticLevel?)level);

    [Fact]
    public async Task SummarizeAsync_NoFacts_ReturnsOverviewAndMetricsSectionsOnly()
    {
        SetupAllFactsEmpty();
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, 50, CancellationToken.None);

        result.SolutionName.Should().Be("TestSolution");
        result.Sections.Should().HaveCount(2); // overview + metrics (both always included)
        result.Markdown.Should().Contain("# TestSolution — Codebase Summary");
        result.Markdown.Should().Contain("*Generated by CodeMap MCP*");
    }

    [Fact]
    public async Task SummarizeAsync_WithRouteFacts_IncludesApiSection()
    {
        SetupAllFactsEmpty();
        SetupFacts(FactKind.Route, "GET /api/orders", "POST /api/orders");
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, 50, CancellationToken.None);

        var apiSection = result.Sections.FirstOrDefault(s => s.Title.Contains("API Surface"));
        apiSection.Should().NotBeNull();
        apiSection!.ItemCount.Should().Be(2);
        result.Stats.EndpointCount.Should().Be(2);
    }

    [Fact]
    public async Task SummarizeAsync_WithConfigFacts_GroupsByTopLevelPrefix()
    {
        SetupAllFactsEmpty();
        SetupFacts(FactKind.Config, "App:MaxRetries|GetValue", "App:Timeout|GetValue", "Db:ConnectionString|GetSection");
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, 50, CancellationToken.None);

        var configSection = result.Sections.FirstOrDefault(s => s.Title.Contains("Configuration"));
        configSection.Should().NotBeNull();
        configSection!.Content.Should().Contain("### App");
        configSection.Content.Should().Contain("### Db");
        result.Stats.ConfigKeyCount.Should().Be(3);
    }

    [Fact]
    public async Task SummarizeAsync_SectionFilter_ReturnsOnlyRequestedSections()
    {
        SetupAllFactsEmpty();
        SetupFacts(FactKind.Route, "GET /health");
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution",
            sectionFilter: ["api", "overview"],
            maxItemsPerSection: 50,
            CancellationToken.None);

        result.Sections.Should().NotContain(s => s.Title.Contains("Configuration"));
        result.Sections.Should().NotContain(s => s.Title.Contains("Key Metrics"));
        result.Sections.Should().Contain(s => s.Title.Contains("Solution Overview"));
        result.Sections.Should().Contain(s => s.Title.Contains("API Surface"));
    }

    [Fact]
    public async Task SummarizeAsync_WithProjectDiagnostics_PopulatesStats()
    {
        SetupAllFactsEmpty();
        SetupProjectDiagnostics(
            new ProjectDiagnostic("SampleApp", Compiled: true, SymbolCount: 500, ReferenceCount: 1200),
            new ProjectDiagnostic("SampleApp.Api", Compiled: true, SymbolCount: 300, ReferenceCount: 800));
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, 50, CancellationToken.None);

        result.Stats.ProjectCount.Should().Be(2);
        result.Stats.SymbolCount.Should().Be(800);
        result.Stats.ReferenceCount.Should().Be(2000);
        result.Markdown.Should().Contain("2 projects");
    }

    [Fact]
    public async Task SummarizeAsync_WithExceptionFacts_IncludesExceptionSection()
    {
        SetupAllFactsEmpty();
        SetupFacts(FactKind.Exception, "ArgumentNullException|throw new", "InvalidOperationException|throw new");
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, 50, CancellationToken.None);

        var exSection = result.Sections.FirstOrDefault(s => s.Title.Contains("Error Handling"));
        exSection.Should().NotBeNull();
        exSection!.Content.Should().Contain("ArgumentNullException");
        result.Stats.ExceptionTypeCount.Should().Be(2);
    }

    [Fact]
    public async Task SummarizeAsync_WithLogFacts_IncludesLoggingSection()
    {
        SetupAllFactsEmpty();
        SetupFacts(FactKind.Log,
            "Processing order {OrderId}|Information",
            "Processing order {OrderId}|Information",  // duplicate template
            "Failed to process {Id}|Error");
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, 50, CancellationToken.None);

        var logSection = result.Sections.FirstOrDefault(s => s.Title.Contains("Logging"));
        logSection.Should().NotBeNull();
        result.Stats.LogTemplateCount.Should().Be(2); // distinct templates
    }

    [Fact]
    public async Task SummarizeAsync_MaxItemsPerSection_IsCapped()
    {
        SetupAllFactsEmpty();
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        // maxItemsPerSection=0 should be clamped to 1
        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, maxItemsPerSection: 0, CancellationToken.None);

        // Verify the store was called with limit >= 1 (not 0)
        await _store.Received().GetFactsByKindAsync(
            Repo, Sha, Arg.Any<FactKind>(), Arg.Is<int>(n => n >= 1), Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task SummarizeAsync_WithAllFacts_IncludesAllSections()
    {
        SetupFacts(FactKind.Route, "GET /api/test");
        SetupFacts(FactKind.Config, "App:Key|GetValue");
        SetupFacts(FactKind.DbTable, "Orders|DbSet<Order>");
        SetupFacts(FactKind.DiRegistration, "IOrderService → OrderService|Scoped");
        SetupFacts(FactKind.Middleware, "UseAuthentication|pos:1");
        SetupFacts(FactKind.RetryPolicy, "RetryAsync(3)|Polly");
        SetupFacts(FactKind.Exception, "ArgumentNullException|throw new");
        SetupFacts(FactKind.Log, "Processing {Id}|Information");
        SetupProjectDiagnostics(new ProjectDiagnostic("SampleApp", true, 100, 200));
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution", null, 50, CancellationToken.None);

        // overview + api + data + config + di + middleware + resilience + exceptions + logging + metrics = 10
        result.Sections.Should().HaveCount(10);
        result.Stats.FactCount.Should().Be(8);
    }

    // ── Empty section placeholder tests ───────────────────────────────────────

    [Fact]
    public async Task SummarizeAsync_RequestedSection_NoData_ShowsPlaceholder()
    {
        // No middleware facts in this codebase
        SetupAllFactsEmpty();
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution",
            sectionFilter: ["middleware"], 50, CancellationToken.None);

        // Should contain a middleware placeholder section
        var middlewareSection = result.Sections.FirstOrDefault(s =>
            s.Title.Contains("Middleware", StringComparison.OrdinalIgnoreCase));
        middlewareSection.Should().NotBeNull("middleware was explicitly requested");
        middlewareSection!.ItemCount.Should().Be(0);
        middlewareSection.Content.Should().Contain("No middleware pipeline detected");
    }

    [Fact]
    public async Task SummarizeAsync_NoFilter_EmptySections_StillOmitted()
    {
        // No facts of any kind → no filter → empty sections should NOT appear
        SetupAllFactsEmpty();
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution",
            sectionFilter: null, 50, CancellationToken.None);

        // Only overview + metrics (no data sections)
        result.Sections.Should().HaveCount(2);
        result.Sections.Should().NotContain(s =>
            s.Title.Contains("Middleware", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task SummarizeAsync_MixedFilter_ShowsDataAndPlaceholders()
    {
        // Has exceptions but no resilience facts
        SetupFacts(FactKind.Exception, "InvalidOperationException|throw new");
        SetupNoFacts(FactKind.RetryPolicy);
        SetupNoFacts(FactKind.Route);
        SetupNoFacts(FactKind.Config);
        SetupNoFacts(FactKind.DbTable);
        SetupNoFacts(FactKind.DiRegistration);
        SetupNoFacts(FactKind.Middleware);
        SetupNoFacts(FactKind.Log);
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution",
            sectionFilter: ["exceptions", "resilience"], 50, CancellationToken.None);

        var exSection = result.Sections.FirstOrDefault(s =>
            s.Title.Contains("Error Handling", StringComparison.OrdinalIgnoreCase));
        var resSection = result.Sections.FirstOrDefault(s =>
            s.Title.Contains("Resilience", StringComparison.OrdinalIgnoreCase));

        exSection.Should().NotBeNull("exceptions section has data");
        exSection!.ItemCount.Should().Be(1);

        resSection.Should().NotBeNull("resilience was explicitly requested");
        resSection!.ItemCount.Should().Be(0);
        resSection.Content.Should().Contain("No retry or circuit-breaker policies detected");
    }

    [Fact]
    public async Task SummarizeAsync_Section_Truncated_ShowsIndicator()
    {
        // 5 DI facts, cap = 2 → should detect truncation
        SetupFacts(FactKind.DiRegistration,
            "IFoo → Foo|Singleton",
            "IBar → Bar|Scoped",
            "IBaz → Baz|Transient",
            "IQux → Qux|Singleton",
            "IFive → Five|Singleton");
        foreach (FactKind kind in Enum.GetValues<FactKind>().Where(k => k != FactKind.DiRegistration))
            SetupNoFacts(kind);
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution",
            sectionFilter: ["di"], maxItemsPerSection: 2, CancellationToken.None);

        var diSection = result.Sections.FirstOrDefault(s =>
            s.Title.Contains("Dependency Injection", StringComparison.OrdinalIgnoreCase));

        diSection.Should().NotBeNull();
        diSection!.Truncated.Should().BeTrue("cap=2, 5 items exist");
        diSection.ItemCount.Should().Be(2);
        diSection.TotalAvailable.Should().BeNull("exact total unknown with +1 probe");
        diSection.Content.Should().Contain("Showing 2 of 2+");
        diSection.Content.Should().Contain("max_items_per_section");
    }

    [Fact]
    public async Task SummarizeAsync_Section_NotTruncated_NoIndicator()
    {
        SetupFacts(FactKind.DiRegistration,
            "IFoo → Foo|Singleton",
            "IBar → Bar|Scoped");
        foreach (FactKind kind in Enum.GetValues<FactKind>().Where(k => k != FactKind.DiRegistration))
            SetupNoFacts(kind);
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution",
            sectionFilter: ["di"], maxItemsPerSection: 50, CancellationToken.None);

        var diSection = result.Sections.FirstOrDefault(s =>
            s.Title.Contains("Dependency Injection", StringComparison.OrdinalIgnoreCase));

        diSection.Should().NotBeNull();
        diSection!.Truncated.Should().BeFalse();
        diSection.TotalAvailable.Should().Be(2);
        diSection.Content.Should().NotContain("Showing");
    }

    [Fact]
    public async Task SummarizeAsync_AllSections_TruncationApplied()
    {
        // 3 items per kind, cap = 1 → all non-empty sections should be truncated
        SetupFacts(FactKind.DiRegistration, "IFoo → Foo|Singleton", "IBar → Bar|Scoped", "IBaz → Baz|Transient");
        SetupFacts(FactKind.Log, "msg1|Information", "msg2|Debug", "msg3|Warning");
        foreach (FactKind kind in Enum.GetValues<FactKind>()
            .Where(k => k != FactKind.DiRegistration && k != FactKind.Log))
            SetupNoFacts(kind);
        SetupProjectDiagnostics();
        SetupSemanticLevel(SemanticLevel.Full);

        var result = await CodebaseSummarizer.SummarizeAsync(
            _store, Repo, Sha, "TestSolution",
            sectionFilter: null, maxItemsPerSection: 1, CancellationToken.None);

        var dataSections = result.Sections.Where(s =>
            s.Title.Contains("Dependency Injection", StringComparison.OrdinalIgnoreCase) ||
            s.Title.Contains("Logging", StringComparison.OrdinalIgnoreCase)).ToList();

        dataSections.Should().HaveCount(2);
        dataSections.Should().AllSatisfy(s => s.Truncated.Should().BeTrue());
        dataSections.Should().AllSatisfy(s => s.ItemCount.Should().Be(1));
    }
}
